// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzPgYk8xCqIv5r4KryfA9Bd-umS8hae5I',
    appId: '1:348371418841:web:7818db90f04ecd1b58c8c8',
    messagingSenderId: '348371418841',
    projectId: 'wallflutter',
    authDomain: 'wallflutter.firebaseapp.com',
    storageBucket: 'wallflutter.appspot.com',
    measurementId: 'G-WK0BSY7J5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ_Yr1QNRaC39KPqP00yeRciA7BWudcQc',
    appId: '1:348371418841:android:fa3c48ba7e2262e958c8c8',
    messagingSenderId: '348371418841',
    projectId: 'wallflutter',
    storageBucket: 'wallflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJUtuu6y0cX-lqD0i8EC8chVyzhG_CzwA',
    appId: '1:348371418841:ios:67c169806351036358c8c8',
    messagingSenderId: '348371418841',
    projectId: 'wallflutter',
    storageBucket: 'wallflutter.appspot.com',
    iosClientId: '348371418841-9tp62b88gl4e8j89f6is66ooqggqsam9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJUtuu6y0cX-lqD0i8EC8chVyzhG_CzwA',
    appId: '1:348371418841:ios:67c169806351036358c8c8',
    messagingSenderId: '348371418841',
    projectId: 'wallflutter',
    storageBucket: 'wallflutter.appspot.com',
    iosClientId: '348371418841-9tp62b88gl4e8j89f6is66ooqggqsam9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
